/// Flutter icons AppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData add_circle_filled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_simple_fill = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData air_purifier_gen = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_today = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_fill = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_fill = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_outlined = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_sharp = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light_bulb_fill = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_fill = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData round_chevron_left = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData round_chevron_right = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scene = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData round_power_settings = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData open_door_fill = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_filled = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound_on_solid = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subtract_circle_filled = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_fill = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv_rounded = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind_power_rounded = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
